{
 "title": "Dashboard Test",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "malicious flows",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(ismalicious_flow == 1) by (switch, flow)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sending Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    { "expr": "sending_rate", "legendFormat": "{{switch}}:{{flow}}" }
   ]
  },
  {
   "title": "Queue Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "queue_time", "legendFormat": "{{switch}} : {{flow}}" }
   ]
  },
  {
   "title": "Switch Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "switch_time", "legendFormat": "{{switch}} : {{flow}}" }
   ]
  },
  {
   "title": "throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    { "expr": "throughput", "legendFormat": "{{switch}} : {{flow}}" }
   ]
  },
  {
   "title": "Weak Learner",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(weak_learner{job=\"p4-orch\"}[1m])",
     "legendFormat": "{{switch}}"
    }
   ]
  }
 ]
}